name: sync_rules_rewriter
resolution: workspace

environment: 
  sdk: ^3.10.0

dependencies:
  source_span: ^1.10.1
  sqlparser: ^0.43.0
  yaml: ^3.1.3
  yaml_edit: ^2.2.3

dev_dependencies:
  test: ^1.29.0

