name: website
description: Standalone editor to translate sync rules to sync streams.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  sync_rules_rewriter:
  jaspr: ^0.22.1
  picocss:
    hosted: https://pub-simonbinder-eu.fsn1.your-objectstorage.com
    version: ^2.1.1
  riverpod: ^3.2.0
  jaspr_riverpod: ^0.4.3

dev_dependencies:
  build_runner: ^2.10.5
  build_web_compilers: ^4.4.7
  jaspr_builder: ^0.22.1
  sass_builder: ^2.4.0
  webdev: ^3.8.0

jaspr:
  mode: client
